export const CATEGORIES = 'categories/categories'
export const CATEGORY = 'categories/category'
export const CATEGORY_NEW = 'categories/category-new'
export const CATEGORY_UPDATE = 'categories/category-update'
export const CATEGORY_DELETE = 'categories/category-delete'
export const CATEGORIES_SET = 'categories/categories-set'

export const USERS = 'users/users'
export const USER = 'users/user'
export const USER_NEW = 'users/user-new'
export const USER_UPDATE = 'users/user-update'
export const USER_DELETE = 'users/user-delete'
export const USERS_SET = 'users/users-set'

export const TOPICS = 'topics/topics'
export const TOPIC = 'topics/topic'
export const TOPIC_NEW = 'topics/topic-new'
export const TOPIC_UPDATE = 'topics/topic-update'
export const TOPIC_DELETE = 'topics/topic-delete'
export const TOPICS_SET = 'topics/topics-set'
